### ISSUE TITLE
Link-uri moarte in Laboratorul 9

### ISSUE THREAD

**Issue by mehanix** [WebToLearn/laborator-tehnici-web#17]
Link-urile de la Laboratorul 9, ex. 2, returneaza 404 Not Found.

https://spring.io/understanding/REST#post
https://spring.io/understanding/REST#put
https://spring.io/understanding/REST#delete

Link laborator: [aici](https://github.com/WebToLearn/laborator-tehnici-web/tree/master/doc/laborator-9)

**Comment by bogminic** [comment]
Am facut update la link-uri.  Multumesc!
